export const pile = [
	['santa', 'rabbit', 'dumbbell', 'guitar', 'diamond', 'badge', 'key', 'trophy'],
	['trophy', 'camera', 'starfish', 'shovel', 'mouse', 'racecar', 'penguin', 'knife'],
	['guitar', 'trumpet', 'owl', 'sword', 'tree', 'balloon', 'dynamite', 'racecar'],
	['bat', 'butterfly', 'phone', 'rocket', 'racecar', 'acorn', 'fox', 'badge'],
	['penguin', 'clip', 'phone', 'key', 'duck', 'clover', 'trumpet', 'apple'],
	['comb', 'shovel', 'scooter', 'guitar', 'cloud', 'hammer', 'duck', 'acorn'],
	['doll', 'dumbbell', 'trumpet', 'acorn', 'bear', 'mouse', 'scorpion', 'tape'],
	['dynamite', 'penguin', 'egg', 'badge', 'earth', 'snail', 'scorpion', 'hammer'],
	['chicken', 'ace', 'binky', 'bullet', 'tape', 'racecar', 'key', 'hammer'],
	['computer', 'sword', 'scorpion', 'ace', 'clover', 'butterfly', 'trophy', 'scooter'],
	['badge', 'hourglass', 'mouse', 'cloud', 'binky', 'cupcake', 'balloon', 'clover'],
	['key', 'cupcake', 'shovel', 'snail', 'butterfly', 'banana', 'owl', 'bear'],
	['orange', 'trophy', 'acorn', 'tree', 'snail', 'binky', 'milk', 'apple'],
	['hammer', 'trophy', 'clip', 'rocket', 'balloon', 'bear', 'well', 'hydrant'],
	['scooter', 'dynamite', 'key', 'bat', 'hydrant', 'wheel', 'mouse', 'milk'],
	['chicken', 'trophy', 'doll', 'hourglass', 'duck', 'dynamite', 'banana', 'fox'],
	['racecar', 'computer', 'earth', 'duck', 'dumbbell', 'orange', 'cupcake', 'hydrant'],
	['camera', 'scorpion', 'guitar', 'apple', 'chicken', 'cupcake', 'rocket', 'wheel'],
	['computer', 'tree', 'rocket', 'cloud', 'doll', 'egg', 'key', 'starfish'],
	['camera', 'diamond', 'fox', 'snail', 'trumpet', 'cloud', 'hydrant', 'ace'],
	['bullet', 'egg', 'bat', 'trumpet', 'cupcake', 'trophy', 'comb', 'lollipop'],
	['bat', 'doll', 'apple', 'earth', 'balloon', 'santa', 'ace', 'shovel'],
	['well', 'duck', 'starfish', 'binky', 'owl', 'bat', 'diamond', 'scorpion'],
	['scooter', 'starfish', 'snail', 'chicken', 'lollipop', 'balloon', 'phone', 'dumbbell'],
	['earth', 'trumpet', 'rabbit', 'banana', 'rocket', 'scooter', 'knife', 'binky'],
	['bullet', 'balloon', 'penguin', 'acorn', 'wheel', 'banana', 'computer', 'diamond'],
	['owl', 'egg', 'knife', 'clover', 'chicken', 'hydrant', 'acorn', 'santa'],
	['orange', 'diamond', 'clover', 'tape', 'rocket', 'lollipop', 'dynamite', 'shovel'],
	['well', 'trumpet', 'chicken', 'milk', 'computer', 'shovel', 'badge', 'fire'],
	['rabbit', 'egg', 'balloon', 'milk', 'duck', 'butterfly', 'tape', 'camera'],
	['balloon', 'orange', 'knife', 'scorpion', 'comb', 'fire', 'fox', 'key'],
	['rocket', 'comb', 'owl', 'hourglass', 'penguin', 'dumbbell', 'milk', 'ace'],
	['lollipop', 'mouse', 'computer', 'hammer', 'apple', 'owl', 'rabbit', 'fox'],
	['apple', 'knife', 'dumbbell', 'butterfly', 'cloud', 'bullet', 'dynamite', 'well'],
	['rabbit', 'bullet', 'phone', 'hydrant', 'hourglass', 'shovel', 'tree', 'scorpion'],
	['well', 'fox', 'santa', 'penguin', 'tape', 'tree', 'cupcake', 'scooter'],
	['dumbbell', 'banana', 'hammer', 'fire', 'camera', 'clover', 'tree', 'bat'],
	['doll', 'sword', 'cupcake', 'phone', 'diamond', 'hammer', 'milk', 'knife'],
	['wheel', 'sword', 'shovel', 'egg', 'clip', 'binky', 'fox', 'dumbbell'],
	['banana', 'clip', 'milk', 'santa', 'racecar', 'lollipop', 'cloud', 'scorpion'],
	['cloud', 'chicken', 'rabbit', 'penguin', 'sword', 'bear', 'orange', 'bat'],
	['apple', 'hourglass', 'scooter', 'diamond', 'fire', 'racecar', 'egg', 'bear'],
	['badge', 'tape', 'apple', 'starfish', 'banana', 'comb', 'hydrant', 'sword'],
	['egg', 'orange', 'ace', 'well', 'banana', 'mouse', 'guitar', 'phone'],
	['clover', 'bullet', 'earth', 'starfish', 'guitar', 'fox', 'milk', 'bear'],
	['doll', 'well', 'snail', 'racecar', 'comb', 'rabbit', 'clover', 'wheel'],
	['camera', 'doll', 'scooter', 'badge', 'bullet', 'orange', 'clip', 'owl'],
	['butterfly', 'mouse', 'clip', 'comb', 'diamond', 'earth', 'chicken', 'tree'],
	['duck', 'fire', 'rocket', 'mouse', 'bullet', 'snail', 'santa', 'sword'],
	['rabbit', 'starfish', 'ace', 'clip', 'acorn', 'cupcake', 'fire', 'dynamite'],
	['wheel', 'badge', 'tree', 'bear', 'duck', 'ace', 'lollipop', 'knife'],
	['guitar', 'hydrant', 'doll', 'lollipop', 'fire', 'penguin', 'binky', 'butterfly'],
	['santa', 'starfish', 'butterfly', 'wheel', 'hourglass', 'trumpet', 'orange', 'hammer'],
	['santa', 'phone', 'camera', 'comb', 'computer', 'bear', 'dynamite', 'binky'],
	['snail', 'knife', 'bat', 'clip', 'guitar', 'tape', 'hourglass', 'computer']
]

export const patterns = [
	[{ top: '8', left: '40', height: '19.5' },
	{ top: '37', left: '35', height: '19.5' },
	{ top: '67', left: '72', height: '19.5' },
	{ top: '74', left: '34', height: '19.5' },
	{ top: '14', left: '13', height: '24' },
	{ top: '55', left: '50', height: '24' },
	{ top: '52', left: '9', height: '29' },
	{ top: '15', left: '61', height: '38.5' }]
]

export const images = [
	'ace',
	'acorn',
	'apple',
	'badge',
	'balloon',
	'banana',
	'bat',
	'bear',
	'binky',
	'bullet',
	'butterfly',
	'camera',
	'chicken',
	'clip',
	'cloud',
	'clover',
	'comb',
	'computer',
	'cupcake',
	'diamond',
	'doll',
	'duck',
	'dumbbell',
	'dynamite',
	'earth',
	'egg',
	'fire',
	'fox',
	'guitar',
	'hammer',
	'hourglass',
	'hydrant',
	'key',
	'knife',
	'lollipop',
	'milk',
	'mouse',
	'orange',
	'owl',
	'penguin',
	'phone',
	'plane',
	'rabbit',
	'racecar',
	'rocket',
	'santa',
	'scooter',
	'scorpion',
	'shovel',
	'snail',
	'starfish',
	'sword',
	'tape',
	'tree',
	'trumpet',
	'well',
	'wheel',
	'trophy'
]

export function initGame() {
	shuffle()
}

function shuffle() {
	var j, x, i = 55
	while (i) {
		j = parseInt(Math.random() * i);
		x = pile[--i]
		pile[i] = pile[j]
		pile[j] = x
	}
}